In [192]:
import pandas as pd

data = pd.read_csv("Salary_prediction_data.csv")

In [193]:
data.drop("Unnamed: 0",axis=1,inplace=True)
data.drop("StudentId",axis=1,inplace=True)

In [194]:
data["Internship"]=data["Internship"].replace({"No" : 0,"Yes":1})
data["Hackathon"]=data["Hackathon"].replace({"No" : 0,"Yes":1})
data["PlacementStatus"]=data["PlacementStatus"].replace({"NotPlaced" : 0,"Placed":1})

C:\Users\Asus\AppData\Local\Temp\ipykernel_36600\2708116101.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data["Internship"]=data["Internship"].replace({"No" : 0,"Yes":1})
C:\Users\Asus\AppData\Local\Temp\ipykernel_36600\2708116101.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data["Hackathon"]=data["Hackathon"].replace({"No" : 0,"Yes":1})
C:\Users\Asus\AppData\Local\Temp\ipykernel_36600\2708116101.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain th

In [195]:
data=data[data["PlacementStatus"]!=0]

data

CGPA  Major Projects  Workshops/Certificatios  Mini Projects  Skills  \
1      8.9               0                        3              2       9   
3      7.5               1                        1              2       8   
4      8.3               1                        2              2       8   
9      7.8               1                        3              2       7   
10     8.3               2                        3              2       9   
...    ...             ...                      ...            ...     ...   
9991   8.4               2                        3              1       8   
9992   8.0               2                        1              2       7   
9996   7.4               0                        1              0       9   
9997   8.4               1                        3              0       7   
9998   8.9               0                        3              2       8   

      Communication Skill Rating  Internship  Hackathon  12th Percentage  \
1                            4.0           1          1               78   
3                            4.4           1          1               81   
4                            4.5           1          1               74   
9                            4.4           1          1               85   
10                           4.8           1          1               82   
...                          ...         ...        ...              ...   
9991                         4.5           1          1               84   
9992                         4.4           1          1               75   
9996                         4.8           0          0               84   
9997                         4.8           1          1               79   
9998                         4.8           1          1               71   

      10th Percentage  backlogs  PlacementStatus   salary  
1                  82         0                1  1000000  
3                  80         0                1   950000  
4                  88         0                1   950000  
9                  86         0                1   450000  
10                 88         0                1  1250000  
...               ...       ...              ...      ...  
9991               87         1                1   900000  
9992               72         1                1   400000  
9996               67         1                1   750000  
9997               81         0                1   550000  
9998               85         0                1   900000  

[4197 rows x 13 columns]

In [196]:
x = data.drop("salary",axis=1)
y=data["salary"]

y.value_counts()

salary
1000000    435
1050000    421
1100000    407
900000     400
950000     382
400000     315
800000     276
450000     269
1150000    233
500000     231
1300000    180
1250000    165
1200000    145
750000     141
700000      93
550000      77
850000      27
Name: count, dtype: int64

In [197]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import *
from sklearn.pipeline import Pipeline
import  numpy as np
lr=Ridge(alpha=0.1)


xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=10)

# pipleline
steps = [("scaler",StandardScaler()),("lr",Ridge(alpha=0.1))]
pipe = Pipeline(steps)
pipe.fit(xtrain,ytrain)
print(ytest)
pipe.predict(xtest)




6054     400000
1821    1000000
7106    1000000
8389    1150000
7397    1300000
         ...   
6263     400000
4397    1000000
6309    1050000
3884    1000000
6103     950000
Name: salary, Length: 840, dtype: int64


array([ 417677.36048789,  906469.49739287, 1166712.7769389 ,
       1156550.87435115, 1129480.58460697,  893385.19149319,
       1180367.87354261,  974858.75782771, 1185224.39899404,
        490069.98066793, 1123209.32548274,  916451.39754422,
       1131269.40953324, 1066516.25003867,  857376.88091321,
       1158433.95703776,  231203.84564209, 1170677.41207451,
        796856.08196165,  890525.74448365,  886652.31513571,
        897074.09264731,  934994.95144819, 1103724.14075533,
       1157549.49853234, 1176240.25210898, 1124916.33829011,
       1197690.73382032,  450181.42236562, 1183691.86444716,
       1191609.29888465, 1180280.74614147,  671369.68021579,
        903226.56990333,  515327.52379955,  874814.42690473,
        812959.28350515, 1134027.99561953, 1174817.21555821,
        572028.03551782,  896404.46002573,  472665.38321553,
        763113.62225227,  943464.75188785,  901034.25048666,
        906106.62597537,  898959.62643436,  444869.2077632 ,
        915194.62990775,

In [198]:
r2 = pipe.score(xtest, ytest)
r2

0.8113959630346381

In [199]:
import joblib

joblib.dump(pipe,"model_salary.joblib")

['model_salary.joblib']

In [200]:
pipe.predict([[8.9, 0, 3, 2, 9, 4.0, 1, 1, 78, 82, 0, 1]])

c:\Users\Asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([1205703.61400032])

In [201]:
loaded_model = joblib.load("model_salary.joblib")


In [202]:
loaded_model.predict([[8.9, 0, 3, 2, 9, 4.0, 1, 1, 78, 82, 0, 1]])

c:\Users\Asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([1205703.61400032])